### ISSUE TITLE
Implement module to remove putative double-counted spikes

### ISSUE THREAD

**Issue by jsiegle** [AllenInstitute/ecephys_spike_sorting#27]
This should run after kilosort_helper, and remove intra- and inter-unit spikes that are overlapping in space and time.

See this issue for more info: https://github.com/MouseLand/Kilosort2/issues/29

**Comment by ldclaar** [comment]
I have tried running phy using the files output by this module and phy gives me an AssertionError. It seems that phy asserts that spike_templates.shape == (ns,). Does it make sense to have this module output a new spike_templates.npy file? Another candidate would be template_features.npy because it also has one dimension equal to the number of spikes.

**Comment by jsiegle** [comment]
Good point, I will fix that.

**Comment by jsiegle** [comment]
@ldclaar This should be fixed in the master branch now. Can you test it out?

**Comment by ldclaar** [comment]
I tested it out, it works now. Thanks!
