### ISSUE TITLE
kilosort post-processing module for KS3 data

### ISSUE THREAD

**Issue by LaurenzMuessig** [AllenInstitute/ecephys_spike_sorting#59]
Hi,

It seems to me at the moment only the quality metric module is compatible with KS3 data. Will there be an update for the kilosort-postprocessing module at some point? Thanks for letting me know.

Cheers

Laurenz

**Comment by jsiegle** [comment]
Hi Laurenz, I've used both the `mean_waveforms` and `quality_metrics` modules with Kilosort3. The `noise_templates` module shouldn't be necessary, as KS3 finds very few (if any) noise units. And I'd like to do more characterization of the KS3 outputs before applying the `kilosort_postprocessing` module, since I'm not sure if double-counted spikes are still an issue with the new algorithm.

Can you describe the bugs you've encountered? They should be straightforward to fix, since the KS3 outputs are quite similar to KS2 (with the exception of missing PCs, at least for now).

**Comment by LaurenzMuessig** [comment]
Hi Josh,

Thanks for quick response. You are right that getting the ks_postprocessing to run seems mainly putting in a few 'try..except..' to deal with the lack of the pc_features in KS3. I was just curious (and lazy) and wondered why you guys hadn't pushed that in the latest update. I'll make the edits myself and let you know if there is some bigger issue.
PS: I am def seeing the issue with double counted spikes quite a lot in my data and as far I understand the spike detection bits haven't changed much between KS2.5 and 3, but mainly the clustering algorithm (but I might be wrong).

**Comment by jsiegle** [comment]
Ok, those changes are now implemented in the master branch. Thanks for pointing this out!
