### ISSUE TITLE
Extracting NPX data recorded with Open Ephys on Linux

### ISSUE THREAD

**Issue by vncntprvst** [AllenInstitute/ecephys_spike_sorting#76]
This is sort of a follow-up on #61 : I was getting JSON file parameter validation errors, which I think are just due to the `extract_from_npx_params` fields `npx_extractor_executable` and `npx_extractor_repo`. The documentation on the [extract_from_npx](https://github.com/AllenInstitute/ecephys_spike_sorting/tree/master/ecephys_spike_sorting/modules/extract_from_npx) module says that NpxExtractor executable is available on Windows only but says nothing about the Github repository. There's no information on that in  `/extract_from_npx/_schemas.py` or `create_input_json.py` either. There's also an indirect reference to that extractor on [the Neuropix-PXI page](https://open-ephys.atlassian.net/wiki/spaces/OEW/pages/963280903/Neuropix-PXI).
Where can this repository be found? Could you clarify the documentation on that topic?
Is there any option to extract that data on Linux? The Open Ephys Python Tools package might be an option ?

**Comment by jsiegle** [comment]
Are you actually saving compressed NPX files directly from the Neuropixels Plugin? We added the ability to do this in an older version of Open Ephys because we were having trouble saving Neuropixels 3a data in the Binary format when running 3 instances of the GUI concurrently on the same machine. But if you're using 1.0 probes (with a PXI system) this should not be necessary (and is not even possible with the latest version).

If you're not using the NPX format, then you can just skip this module, which should fix the validation errors.

If you *are* using the NPX format, then you should decompress the files on the machine you used for data collection using the executable available [here](https://github.com/AllenInstitute/ecephys_spike_sorting/tree/master/ecephys_spike_sorting/modules/extract_from_npx/NpxExtractor/Release).
